
function mydefaults()
    close all;
    randn('state',0);
    rand('state',0);
    height = 2/3;
    set(0,...
    'defaultfigureposition',[180 100 800 800*height],...
    'defaultaxeslinewidth',.5,...
    'defaultaxesfontsize',16,...
    'defaultlinelinewidth',2,...
    'defaultpatchlinewidth',1,...
    'defaultlinemarkersize',8,...
    'defaulttextinterpreter','tex');
end
